spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}}/
    name: ${{ secrets.POSTGRES_DB }}
    username: ${{ secrets.POSTGRES_USER }}
    password: ${{ secrets.POSTGRES_PASSWORD }}
  jpa:
    show-sql: false
