server:
  port: 8080

spring:
  profiles:
    active: @profileActive@
  application:
    name: CarPartsCatalog
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
